#################################
###       Masse molaire       ###
#################################
POST http://127.0.0.1:8000/calculation_masse_molaire HTTP/1.1
Content-Type: application/json

{
    "Compose":"H2SO4"
}


#################################
###            Mole           ###
#################################
POST http://127.0.0.1:8000/calculation_mol HTTP/1.1
Content-Type: application/json

{
    "Compose":"H2SO4",
    "Masse":"20"
}



POST http://127.0.0.1:8000/enigma HTTP/1.1
Content-Type: application/json

{
    "Compose":"H2SO4",
    "Masse":"20",
    "Mole":"",
    "Volume":""

}
